Partition promtail role
metal-stack/metal-roles pull request #169
Opened 2023-04-26 12:12 UTC by thanche1

2023-04-27 09:10 UTC, robertvolkmann requested changes

2023-04-27 09:10 UTC, robertvolkmann commented on partition/roles/promtail/README.md
> +# TODO
Still empty.

2023-04-27 09:10 UTC, robertvolkmann commented on partition/roles/promtail/defaults/main.yml
> +# TODO: move to release vector
```suggestion
```

2023-04-27 09:10 UTC, robertvolkmann commented on partition/roles/promtail/templates/promtail.yaml.j2
> +  - url: {{ promtail_loki_push_endpoint }}/loki/api/v1/push
```suggestion
  - url: {{ promtail_loki_push_endpoint }}
```
`/loki/api/v1/push` should be part of `promtail_loki_push_endpoint`.

2023-04-27 09:10 UTC, robertvolkmann commented on partition/roles/promtail/templates/promtail.yaml.j2
> +  #         action: inc
Do we need the above lines?

2023-04-27 09:10 UTC, robertvolkmann commented on defaults/main.yaml
> -    event_exporter_tag: "docker-images.third-party.control-plane.event-exporter.tag"
These exporters are still in use.

2023-04-27 09:10 UTC, robertvolkmann commented on control-plane/roles/logging/templates/loki_ingress.yaml
> -{% endif %}
Why we're switched from client certificate to basic authentication?

2023-04-27 09:28 UTC, robertvolkmann requested changes
Should promtail be moved to the monitoring directory?

2023-04-27 09:28 UTC, robertvolkmann commented on partition/roles/monitoring/ipmi-exporter/templates/config.yml
> +modules:
How is using this file?

2023-05-02 15:32 UTC, robertvolkmann approved these changes

2023-05-03 12:50 UTC, Gerrit91 approved these changes

2023-05-03 12:50 UTC, merged