Make basic_auth for prometheus and promtail optional
metal-stack/metal-roles pull request #316
Opened 2024-09-10 07:12 UTC by simcod

2024-09-10 09:53 UTC, Gerrit91 approved these changes
As there's no documentation at all for this role, we can simply merge it. Would be nice to have some docs though for the future.

2024-09-11 11:20 UTC, robertvolkmann requested changes

2024-09-11 11:20 UTC, robertvolkmann commented on partition/roles/monitoring/prometheus/templates/prometheus.yaml.j2
> +  {% if prometheus_remote_write_basic_auth_username and prometheus_remote_write_basic_auth_password %}
```suggestion
  {% if prometheus_remote_write_basic_auth_username is defined and prometheus_remote_write_basic_auth_password is defined %}
```

2024-09-11 11:20 UTC, robertvolkmann commented on partition/roles/promtail/templates/promtail.yaml.j2
> +    {% if promtail_loki_basic_auth_username and promtail_loki_basic_auth_password %}
```suggestion
    {% if promtail_loki_basic_auth_username is defined and promtail_loki_basic_auth_password is defined %}
```

2024-09-11 11:30 UTC, merged